POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "test",
  "number": "69696969"
}
###
PUT http://localhost:3001/api/persons/60dc6b4f8059e377785db358
Content-Type: application/json

{
  "name": "test",
  "number": "69696969"
}


###
DELETE http://localhost:3001/api/persons/3

###
GET http://localhost:3001/api/persons/5

###
GET http://localhost:3001/api/persons
